# Module: NumPy Assignments
## Lesson: NumPy




### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [ ]:
import numpy as np
arr1=np.random.randint(1,21,size=(5,5))
print(f"arr1={arr1}")
arr1[:,2]=1
print("\n")
print(f"new arr1={arr1}")

arr1=[[ 3 13 14  1 19]
 [ 3 16  1 10 18]
 [ 6  4 15 13  9]
 [10 20  2 10 15]
 [ 5 15  1 13  9]]


new arr1=[[ 3 13  1  1 19]
 [ 3 16  1 10 18]
 [ 6  4  1 13  9]
 [10 20  1 10 15]
 [ 5 15  1 13  9]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [5]:
import numpy as np
arr2=np.arange(1,17).reshape((4,4))
np.fill_diagonal(arr2,0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [9]:
import numpy as np
arr1=np.arange(1,37).reshape((6,6))
sub=arr1[2:5,1:4]
print(sub)

[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.`

In [24]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.arange(1,26).reshape(5,5)
print("Original array:")
print(array)



# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Border elements:
[ 1  2  3  4  5 21 22 23 24 25  6 11 16 10 15 20]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [28]:
arr1=np.random.randint(1,21,size=(3,4))
arr2=np.random.randint(1,21,size=(3,4))
print(arr1)
print(arr2)
print(f"addition=\n{arr1+arr2}")
print(f"sub=\n{arr1-arr2}")
print(f"mul=\n{arr1*arr2}")
print(f"div=\n{arr1/arr2}")

[[ 7  4  1 11]
 [17  5 15 14]
 [ 8 19  5 19]]
[[12  9  1 16]
 [16 12  5  2]
 [10  9 17 19]]
addition=
[[19 13  2 27]
 [33 17 20 16]
 [18 28 22 38]]
sub=
[[ -5  -5   0  -5]
 [  1  -7  10  12]
 [ -2  10 -12   0]]
mul=
[[ 84  36   1 176]
 [272  60  75  28]
 [ 80 171  85 361]]
div=
[[0.58333333 0.44444444 1.         0.6875    ]
 [1.0625     0.41666667 3.         7.        ]
 [0.8        2.11111111 0.29411765 1.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [33]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
row_sum=np.sum(arr,axis=1)
col_sum=np.sum(arr,axis=0)
print(f"sum of row={row_sum}")
print(f"sum of col={col_sum}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of row=[10 26 42 58]
sum of col=[28 32 36 40]
